# Generated by Django 3.0.7 on 2020-09-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.TextField(blank=True, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='hoge',
            field=models.TextField(blank=True, verbose_name='hoge'),
        ),
    ]
