# Generated by Django 3.0.7 on 2020-09-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200913_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='hoge',
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='author',
            field=models.CharField(max_length=40, verbose_name='著者'),
        ),
    ]
