# Generated by Django 3.0.7 on 2020-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200913_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='slug',
            field=models.CharField(blank=True, max_length=20, verbose_name='URL'),
        ),
    ]
