# Generated by Django 3.0.7 on 2020-09-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_blogarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='slug',
            field=models.CharField(max_length=20, verbose_name='URL'),
        ),
    ]
