# Generated by Django 3.0.7 on 2020-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200922_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='summary',
            field=models.TextField(verbose_name='概要'),
        ),
    ]
