# Generated by Django 3.0.7 on 2020-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200922_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
